### ISSUE TITLE
Will OTF file work?

### ISSUE THREAD

**Issue by jsgao0** [ynakajima/ttf.js#11]
At first, thank you for sharing this and it help me to finish the project. On the one hand, it works on almost TTF files. On the other hand, it couldn't parse OTF files. However, OTF files are more popular than other Font files in these days. Hence, I probably do otf.js which might fork from ttf.js which you've done.

But... I don't know how to start because I have no idea at the first step. Could you please tip me how to start if you available? I will extremely appreciate that.  :)

**Comment by ynakajima** [comment]
Thank you for comment. 
Seems opentype.js to work well for OpenType Font.

https://github.com/nodebox/opentype.js
